server:
  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
    - type: http
      port: 8081

# Logging settings.
logging:
  level: INFO
  loggers:
    com.example.app: DEBUG

template: Hello, %s!
defaultName: Stranger
